version: '2.1'

services:
  agilan-nod-red:
    image: agilan-nod-red
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node red.js --settings settings.js